# Generated by Django 4.0.3 on 2022-04-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='About',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
