# Generated by Django 4.0.3 on 2022-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_rename_createdon_posts_postedon_comments_commentedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='HasComment',
            field=models.BooleanField(null=True),
        ),
    ]
