# Generated by Django 4.0.3 on 2022-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_posts_hascomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='LikeCount',
            field=models.IntegerField(null=True),
        ),
    ]
