# Generated by Django 4.0.3 on 2022-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_posts_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='PageImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='ProfilePic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
