# Generated by Django 4.0.3 on 2022-04-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_pages_pageimage_posts_image_userdetails_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='About',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
