# Generated by Django 4.0.3 on 2022-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_alter_userdetails_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='About',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Body',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
